#!/bin/bash

url="https://www.clarin.si:443/repository/xmlui/handle/11356/1041"
subject="restarting clarin.si"
target="inflected form"
recipient="repo-technical@clarin.si"

cd /tmp
wget -o check_website.log -O check_website.html $url

if ! grep -q "HTTP request sent, awaiting response... 200 OK" check_website.log; then
   if ! grep -q "$target" check_website.html; then
       date=`date`
       ps=`ps aux`
       down=""
       if ! grep -q "postgresql" <<< $ps; then
           down="$down postgresql"
       fi
       if ! grep -q "tomcat" <<< $ps; then
           down="$down tomcat"
       fi
       if ! grep -q "apache" <<< $ps; then
           down="$down apache"
       fi
       if ! grep -q "handle" <<< $ps; then
          down="$down handle"
       fi
       cd /project/lindat-dspace/source/utilities/project_helpers/scripts
       message="subject:$subject\nCLARIN.SI appears to be down.\n\nDate:$date\nURL:$url\nTarget string:$target\nProcesses missing:$down\n\nRestarting: sudo make restart ..."
       echo -e "$message" | /usr/sbin/sendmail "$recipient"
       make restart
   fi
fi
